### ISSUE TITLE
Strange offset in GameTest position

### ISSUE THREAD

**Issue by Edivad99** [neoforged/NeoForge#1948]
**Minecraft Version:** 1.21.3

**NeoForge Version:**  21.3.63

**Steps to Reproduce:**
1. Use the `/test pos` command

![Image](https://github.com/user-attachments/assets/b633a75f-43ef-48d5-9ac2-b0a98318aa59)

2. Set the value reported by the command to the code
![Image](https://github.com/user-attachments/assets/bf2492de-71dc-40bc-9d30-444b103f4f72)

3. The test fails because it does not find the button
![Image](https://github.com/user-attachments/assets/0ed8655a-c090-4140-837d-89b69c48c990)

This is the code that was in 1.21.1
```java
public BlockPos absolutePos(BlockPos pos) {
    BlockPos blockpos = this.testInfo.getStructureBlockPos();
    BlockPos blockpos1 = blockpos.offset(pos);
    return StructureTemplate.transform(blockpos1, Mirror.NONE, this.testInfo.getRotation(), blockpos);
}
```
and this in 1.21.3
```java
public BlockPos absolutePos(BlockPos pos) {
    BlockPos blockpos = this.testInfo.getTestOrigin();
    BlockPos blockpos1 = blockpos.offset(pos);
    return StructureTemplate.transform(blockpos1, Mirror.NONE, this.testInfo.getRotation(), blockpos);
}
```
When doing a test, blockpos gets two different values ​​and it is probably the cause of the problem

**Comment by ChampionAsh5357** [comment]
Okay, so I see the issue now. Basically, the way that `TestCommand#showPos` works is that it gets the position relative to the structure block. However, `getTestOrigin` gets the position relative to the corner of the test boundary, which by default is one above the structure block, making the test position inputted wrong as it doesn't take into account the structure offset. This is fixed in the 1.21.5 snapshots, but it can be backported.

**Comment by ChampionAsh5357** [comment]
Bug report on 1.21.5 snapshot that was resolved: https://bugs.mojang.com/browse/MC-279599

**Comment by ChampionAsh5357** [comment]
Bug report on 1.21.5 snapshot that was resolved: https://bugs.mojang.com/browse/MC-279599

**Comment by Edivad99** [comment]
@ChampionAsh5357 
The problem remains.
When I run `/test pos`, it now returns 0,2,3.
But if I run the test it fails and the red block is rendered at 0,3,3
`wyetrackpassive failed! Expected button at 10,60,2 (relative: 0,3,3) (t=0)`

**Comment by Edivad99** [comment]
Even if it writes 0,3,3 I put 0,2,3
```java
@GameTest(template = "wye_track_passive")
public static void wyeTrackPassive(GameTestHelper helper) {
    helper.pressButton(0, 2, 3);
    helper.succeedWhenEntityPresent(EntityType.MINECART, 3, 2, 5);
}
```

**Comment by ChampionAsh5357** [comment]
I am unable to verify after the PR. You are welcome to provide the NBT file in question so that I may further test.

**Comment by ChampionAsh5357** [comment]
I am unable to verify after the PR. You are welcome to provide the NBT file in question so that I may further test.

**Comment by Edivad99** [comment]
https://github.com/railcraft-reborn/railcraft/blob/1.21.x/src/test/resources/data/railcraft/structure/wye_track_passive.nbt

**Comment by Edivad99** [comment]
Ok, strangely enough I had to run a `gradle build` and then it worked

**Comment by Edivad99** [comment]
If I change a coordinate by decreasing the y by 1 and immediately run GameTestServer, it fails.
While if I change and do a gradle build and then run GameTestServer it works.
Is it normal?

**Comment by ChampionAsh5357** [comment]
To me, that suggests there's something wrong with the compilation process of your buildscript and that the classes in the build folder aren't getting updated.

Running the tests on my end shows no issue, so there's probably something weird going on with your buildscript.

**Comment by ChampionAsh5357** [comment]
To me, that suggests there's something wrong with the compilation process of your buildscript and that the classes in the build folder aren't getting updated.

Running the tests on my end shows no issue, so there's probably something weird going on with your buildscript.

**Comment by Edivad99** [comment]
I don't know, it doesn't seem strange to me. https://github.com/railcraft-reborn/railcraft/blob/1.21.3%2B/build.gradle

**Comment by ChampionAsh5357** [comment]
Hmm, I've done a bit of testing, but I'm still having trouble replicating your situation. My best guess is that something strange is happening when the source set is applied to the run configurations such that it doesn't use the changes unless explicitly told to by building. Best I can suggest is try invalidating the gradle caches; otherwise, it would probably require a deep dive or someone with more knowledge than me to take a look at the situation.

**Comment by ChampionAsh5357** [comment]
Hmm, I've done a bit of testing, but I'm still having trouble replicating your situation. My best guess is that something strange is happening when the source set is applied to the run configurations such that it doesn't use the changes unless explicitly told to by building. Best I can suggest is try invalidating the gradle caches; otherwise, it would probably require a deep dive or someone with more knowledge than me to take a look at the situation.
