### ISSUE TITLE
PerWorld configs should create a "defaultConfig" config first

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#82]
o/
I wasn't going to implement this myself but if configs get reworked as #32 was FINALLY found an seen as a "issue" and not just seen as "don't use notepad++".

here is another thing that modpack devs will kiss your feet for.
Server configs will only be created when you create a world.

Which is fine. I get that per instance configs make sense.
But while i am writing my own config system (will launch soon xD) i found something that forges configs could do a LOT better.
And thought of sharing the idea.

Instead of ONLY creating a server config upon world creation in 1 specific instance.
How about you create upon game load a server config in the "defaultConfigs" folder?
And when a world loads it first copies from the "defaultConfigs" folder if present?
And just append differences there.

This would allow modpack devs to provide global configs to their pack without having to install another mod.
Or is there a reason why forge creates the "defaultConfigs" folder in runtime?

Anyways.
That is something a TON of people would love to see.

Also and if people just want to refresh the "defaultconfigs" delete the file. It doesn't interfere with "existing copies" just "fresh one" would copy the new config entry.

**Comment by TelepathicGrunt** [comment]
Talks about server configs and more are being discussed in Neo discord. There are different ideas bounced around about how to better organize or rethink configs overall. When the plans gets set in motion is to be determined. Neo is not quite ready to tackle configs at this moment 
https://discord.com/channels/313125603924639766/1134858821160931471

**Comment by Speiger** [comment]
@TelepathicGrunt honestly this config system just needs its bugs fixed and a default system provided for server configs and then it is honestly really good.
A config gui would be nice as default but there is just such good alternatives out there.

It was a suggestion after all.

Good that discussions were now made public about it.

**Comment by Technici4n** [comment]
We implemented https://github.com/neoforged/NeoForge/pull/376 which will place the server config in the standard config folder, and allow users to override it on a per-world basis.

**Comment by Speiger** [comment]
@Technici4n 🤦 Really? That isn't helping anyone.
It doesn't solve the underlying issue that configs only get created after you created a world.

The entire idea is that you don't have to create a world to set default values.

The problem you are ignoring is: Nobody will use that feature because its not visible to the user in any shape or form.
And that readme is useless since 99% of the users will not read it.

You guys had one job.
- 1: Create the configs in the default configs folder upon game startup (if missing)
- 2: When a world is created simply copy paste the files into the per world config folder.
- 3: Done!

Ugh...
Please reopen this issue otherwise I will simply create another issue requesting the same as right now because the fix wasn't a FIX.
It was a "I pretend to know what the issue was and do absolutely nothing"

**Comment by gigaherz** [comment]
There's no need for defaultconfigs folder anymore. The config file will always live in the main config folder unless you choose to make it per-world.

**Comment by TelepathicGrunt** [comment]
Config should be applied to all worlds by default and then if user wants it per world, would copy it into the world in question. That’s the logical and desired outcome people wanted. The change is good.

**Comment by Speiger** [comment]
@gigaherz @TelepathicGrunt so all serverside configs should by default be "common" in type unless you really need a server specific config.

I do assume common configs do get synced to the client too. If not, then it should be changed.

Anyways thank you for that information.

The argument is over for me, I am going to drop it.
I am not using forge configs anymore anyways for multiple reasons...
(No loading control, Server Configs sucking, No expansion support, and no dynamic config support, which i all require)

**Comment by TelepathicGrunt** [comment]
Copying from discord, this is the config behaviors I would’ve preferred:
![IMG_0715](https://github.com/neoforged/NeoForge/assets/40846040/4660e296-3f55-4e72-a8ca-70a1286a43f3)

More user friendly. Gives control to pack makers for world configs. Is more intuitive for how it works. Easy to see which configs can be overridden. Allows user to manually opt out of pack maker’s defaults permanently for a specific world. I don’t see much downsides in my picture proposed and ticks most checkboxes of what people want out of the config system

**Comment by Speiger** [comment]
@TelepathicGrunt to answer that.
That would be something i can agree on.
